spring:
  application:
    name: recipes

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER}

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080

